#!/bin/bash

# Demo script showing three Hindu calendar output formats
# Matches the user's request for "create option list of three calendar output like as screenshot"

echo "==========================================================="
echo "    🌙☀️  HINDU CALENDAR OUTPUT FORMAT DEMO  🌙☀️"
echo "==========================================================="
echo ""
echo "This demonstration shows the three output format options"
echo "available for Hindu calendar (Panchanga) calculations:"
echo ""
echo "1. 📊 TABLE FORMAT    - Detailed traditional Panchanga display"
echo "2. 📋 COMPACT FORMAT  - Matches classical Pancanga3.14.pl style"
echo "3. 💾 DATA FORMATS    - CSV and JSON for data processing"
echo ""

# Test parameters
DATE_FROM="2025-07-20"
DATE_TO="2025-07-25"
LATITUDE="28.6139"
LONGITUDE="77.2090"

echo "==========================================================="
echo "TEST PARAMETERS:"
echo "Date Range: $DATE_FROM to $DATE_TO"
echo "Location: New Delhi, India ($LATITUDE°N, $LONGITUDE°E)"
echo "Calendar System: Luni-Solar (traditional)"
echo "Ayanamsa: Lahiri/Chitrapaksha"
echo "==========================================================="
echo ""

echo "Building the application..."
make clean && make -j$(nproc)
if [ $? -ne 0 ]; then
    echo "❌ Build failed. Please check compilation errors."
    exit 1
fi

echo ""
echo "🔷 FORMAT 1: TABLE FORMAT (Detailed Traditional Panchanga)"
echo "==========================================================="
echo "Command: ./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format table"
echo ""
./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format table

echo ""
echo ""
echo "🔶 FORMAT 2: COMPACT FORMAT (Classical Pancanga3.14.pl Style)"
echo "==========================================================="
echo "Command: ./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format compact"
echo ""
./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format compact

echo ""
echo ""
echo "🔸 FORMAT 3: CSV FORMAT (Data Processing)"
echo "==========================================================="
echo "Command: ./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format csv"
echo ""
./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format csv

echo ""
echo ""
echo "🔹 FORMAT 4: JSON FORMAT (Structured Data)"
echo "==========================================================="
echo "Command: ./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format json | head -30"
echo ""
./bin/horoscope_cli --panchanga-range $DATE_FROM $DATE_TO --lat $LATITUDE --lon $LONGITUDE --panchanga-format json | head -30
echo "[...output truncated for brevity...]"

echo ""
echo ""
echo "📊 FORMAT COMPARISON SUMMARY"
echo "==========================================================="
echo ""
echo "FORMAT    | USE CASE                     | FEATURES"
echo "----------|------------------------------|-----------------------------"
echo "table     | Traditional Panchanga study  | • Detailed descriptions"
echo "          | Human-readable output        | • Timing information"
echo "          | Religious/cultural use       | • Festival notifications"
echo "          |                              | • Muhurta assessments"
echo ""
echo "compact   | Classical text format        | • Matches Pancanga3.14.pl"
echo "          | Academic/scholarly use       | • Julian & Gregorian dates"
echo "          | Traditional calculations     | • Kali & Vikrama years"
echo "          |                              | • Paksha with tithi values"
echo ""
echo "csv       | Data analysis                | • Spreadsheet compatible"
echo "          | Bulk processing              | • Statistical analysis"
echo "          | Database import              | • Programming interfaces"
echo ""
echo "json      | Modern applications          | • Web applications"
echo "          | API integrations             | • Mobile apps"
echo "          | Software development         | • Structured data exchange"
echo ""

echo "🎯 USAGE RECOMMENDATIONS"
echo "==========================================================="
echo ""
echo "• Use TABLE format for traditional Panchanga study and daily religious observance"
echo "• Use COMPACT format when you need the classical academic/scholarly output style"
echo "• Use CSV format for data analysis, statistical studies, or database import"
echo "• Use JSON format for modern software applications and web services"
echo ""

echo "🔧 COMMAND TEMPLATES"
echo "==========================================================="
echo ""
echo "# Single date calculation (detailed)"
echo "./bin/horoscope_cli --panchanga --date 2025-07-25 --lat 28.6139 --lon 77.2090"
echo ""
echo "# Date range with classical format"
echo "./bin/horoscope_cli --panchanga-range 2025-07-20 2025-07-25 --lat 28.6139 --lon 77.2090 --panchanga-format compact"
echo ""
echo "# Export to CSV file"
echo "./bin/horoscope_cli --panchanga-range 2025-07-01 2025-07-31 --lat 28.6139 --lon 77.2090 --panchanga-format csv > july_2025_panchanga.csv"
echo ""
echo "# Different calendar systems"
echo "./bin/horoscope_cli --panchanga-range 2025-07-20 2025-07-25 --lat 28.6139 --lon 77.2090 --calendar-system lunar --panchanga-format compact"
echo "./bin/horoscope_cli --panchanga-range 2025-07-20 2025-07-25 --lat 28.6139 --lon 77.2090 --calendar-system solar --panchanga-format compact"
echo "./bin/horoscope_cli --panchanga-range 2025-07-20 2025-07-25 --lat 28.6139 --lon 77.2090 --calendar-system luni-solar --panchanga-format compact"
echo ""

echo "✅ All format demonstrations completed successfully!"
echo "==========================================================="
echo ""
echo "📚 For more information, see:"
echo "• THREE_CALENDAR_SYSTEMS_LIST.md"
echo "• CALENDAR_SYSTEMS_COMPARISON.md"
echo "• ENHANCED_HINDU_CALENDAR.md"
echo ""
echo "Created: $(date)"
echo "==========================================================="
