#!/bin/bash

# Demo script for Myanmar Monthly Calendar inspired by mmcal.blogspot.com
# Shows different monthly calendar output formats

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "    🇲🇲✨ MYANMAR MONTHLY CALENDAR DEMO ✨🇲🇲"
echo "              Inspired by https://mmcal.blogspot.com/"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "This demonstration shows various Myanmar monthly calendar output formats"
echo "similar to the design from mmcal.blogspot.com website."
echo ""

# Test parameters
YEAR="2024"
MONTH="04"  # April 2024
MONTH_STR="$YEAR-$MONTH"

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "DEMO PARAMETERS:"
echo "Date: April $YEAR (Gregorian)"
echo "Location: Yangon, Myanmar (default coordinates)"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "Building the application..."
make clean && make -j$(nproc)
if [ $? -ne 0 ]; then
    echo "❌ Build failed. Please check compilation errors."
    exit 1
fi

echo ""
echo "🔷 FORMAT 1: TRADITIONAL MYANMAR CALENDAR LAYOUT"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "Command: ./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format traditional"
echo ""
./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format traditional

echo ""
echo ""
echo "🔶 FORMAT 2: MODERN VISUAL LAYOUT"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "Command: ./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format modern"
echo ""
./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format modern

echo ""
echo ""
echo "🔸 FORMAT 3: COMPACT REFERENCE VIEW"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "Command: ./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format compact"
echo ""
./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format compact

echo ""
echo ""
echo "🔹 FORMAT 4: BLOG-STYLE LAYOUT (mmcal.blogspot.com inspired)"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "Command: ./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format blog-style"
echo ""
./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format blog-style

echo ""
echo ""
echo "📊 FORMAT COMPARISON SUMMARY"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "FORMAT      | USE CASE                     | FEATURES"
echo "------------|------------------------------|-----------------------------"
echo "traditional | Traditional Myanmar display  | • Myanmar script headers"
echo "            | Cultural authenticity        | • Detailed astrological info"
echo "            | Religious observance         | • Festival notifications"
echo "            |                              | • Classical layout style"
echo ""
echo "modern      | Contemporary users           | • Clean visual design"
echo "            | Easy reading                 | • Color-coded indicators"
echo "            | Quick reference              | • Modern typography"
echo "            |                              | • Streamlined information"
echo ""
echo "compact     | Space-constrained displays   | • Minimal space usage"
echo "            | Quick lookup                 | • Essential info only"
echo "            | Terminal/mobile friendly     | • Simple formatting"
echo "            |                              | • Fast rendering"
echo ""
echo "blog-style  | Web publishing               | • mmcal.blogspot.com style"
echo "            | Documentation                | • Detailed monthly highlights"
echo "            | Educational content          | • Statistics and summaries"
echo "            |                              | • Rich presentation"
echo ""

echo "💾 DATA EXPORT FORMATS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "# Export to JSON (for web applications)"
echo "./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format json"
echo ""
echo "# Export to CSV (for spreadsheet analysis)"
echo "./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format csv"
echo ""
echo "# Export to HTML (for web display)"
echo "./bin/horoscope_cli --myanmar-monthly $MONTH_STR --myanmar-monthly-format html"
echo ""

echo "🎯 USAGE RECOMMENDATIONS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "• Use TRADITIONAL format for authentic Myanmar calendar experience"
echo "• Use MODERN format for contemporary applications and easy reading"
echo "• Use COMPACT format for terminals, mobile devices, or quick reference"
echo "• Use BLOG-STYLE format for educational content or web publishing"
echo "• Use JSON format for web applications and programming interfaces"
echo "• Use CSV format for data analysis and spreadsheet applications"
echo "• Use HTML format for web display with CSS styling"
echo ""

echo "🔧 COMMAND TEMPLATES"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "# Current month Myanmar calendar"
echo "./bin/horoscope_cli --myanmar-monthly \$(date +'%Y-%m')"
echo ""
echo "# Specific month with format"
echo "./bin/horoscope_cli --myanmar-monthly 2024-04 --myanmar-monthly-format traditional"
echo ""
echo "# Export to file"
echo "./bin/horoscope_cli --myanmar-monthly 2024-04 --myanmar-monthly-format json > april_2024_myanmar.json"
echo ""
echo "# Multiple months (script example)"
echo "for month in {01..12}; do"
echo "  ./bin/horoscope_cli --myanmar-monthly 2024-\$month --myanmar-monthly-format compact"
echo "done"
echo ""

echo "✅ All Myanmar monthly calendar format demonstrations completed successfully!"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 For more information about Myanmar calendar system, see:"
echo "• MYANMAR_CALENDAR_VERIFICATION.md"
echo "• https://mmcal.blogspot.com/ (original inspiration)"
echo "• yan9a/mmcal repository (algorithmic reference)"
echo ""
echo "🌟 New feature inspired by mmcal.blogspot.com design"
echo "Created: $(date)"
echo "═══════════════════════════════════════════════════════════════════════════════"
